[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 6, y = 0 }
[terminal]
shell.program = "/usr/bin/tmux"

[font]
size = 10
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "SemiBold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

